project/src/main/java/com/yapp/project/account/controller/AuthController.java
project/src/main/java/com/yapp/project/account/domain/Account.java
project/src/main/java/com/yapp/project/account/service/AuthService.java
project/src/main/java/com/yapp/project/base/Message.java
project/src/main/java/com/yapp/project/base/PrefixType.java
project/src/main/java/com/yapp/project/base/StatusEnum.java
project/src/main/java/com/yapp/project/config/exception/EmailDuplicateException.java
project/src/main/java/com/yapp/project/config/exception/GlobalExceptionHandler.java

- setter 대신해서 updateLastLoginAccount 메소드를 추가함으로써 마지막 로그인 날짜 갱신 작업 실시
- 에러처리에 관한 정리 및 응답할 때 보낼 포맷 설정(의논하여 변경할 예정)
- Redis에 리플레시 토큰을 저장할 때 아이디: 값 으로 넣는 것으로 하는데, 아이디 앞에 접미사로 설정하여 후에 redis를 다른 용도로 썼을 때 차질이 없도록 했다. 만약 이 방법이 마음에 안들면 hash로 변경할 예정.

[YAPPIOS-19]  기본 틀 작업 

---

src/main/java/com/yapp/project/account/service/AuthService.java
src/main/java/com/yapp/project/config/exception/Content.java
src/test/java/com/yapp/project/account/controller/AuthControllerTest.java
src/test/java/com/yapp/project/account/service/AuthServiceTest.java

[YAPPIOS-23] 테스트케이스 추가 및 에러 메세지 하나의 클래스에 통합

---

src/main/java/com/yapp/project/organization/domain/Organization.java
src/main/java/com/yapp/project/organization/domain/dto/OrganizationDto.java
src/main/java/com/yapp/project/organization/service/GroupService.java

- 인터페이스로 어떤 메소드가 필요할 지 작업
- 필요할 dto 추가
- Organization 모델에 인원 수를 세기 위한 onetomany 칼럼 추가

[YAPPIOS-36] 그룹 관련 스케치 작업

---

src/main/java/com/yapp/project/account/controller/AccountController.java
src/main/java/com/yapp/project/account/controller/AuthController.java
src/main/java/com/yapp/project/account/domain/Account.java
src/main/java/com/yapp/project/account/domain/dto/AccountRequestDto.java
src/main/java/com/yapp/project/account/domain/dto/AccountResponseDto.java
src/main/java/com/yapp/project/account/domain/dto/NicknameRequestDto.java
src/main/java/com/yapp/project/account/domain/dto/SocialRequestDto.java
src/main/java/com/yapp/project/account/domain/dto/SocialResponseDto.java
src/main/java/com/yapp/project/account/domain/dto/SocialSignUpRequestDto.java
src/main/java/com/yapp/project/account/domain/repository/AccountRepository.java
src/main/java/com/yapp/project/account/service/AccountService.java
src/main/java/com/yapp/project/account/service/AuthService.java
src/main/java/com/yapp/project/aux/note/account/AccountNotes.java
src/main/java/com/yapp/project/config/exception/Content.java
src/main/java/com/yapp/project/config/exception/GlobalExceptionHandler.java
src/main/java/com/yapp/project/config/exception/account/DuplicateException.java
src/test/java/com/yapp/project/account/controller/AuthControllerTest.java
src/test/java/com/yapp/project/account/service/AuthServiceTest.java

- 소셜 로그인 추가
- 닉네임 Validation Controller 추가
- swagger 설명 부분 추가

[YAPPIOS-32] 소셜 로그인 기능 추가 (암호화 미적용)

---

src/test/java/com/yapp/project/account/service/AuthServiceTest.java

[YAPPIOS-39] 테스트케이스 오류 수정

---

src/main/java/com/yapp/project/account/controller/AccountController.java
src/main/java/com/yapp/project/account/controller/AuthController.java
src/main/java/com/yapp/project/account/domain/Account.java
src/main/java/com/yapp/project/account/domain/dto/AccountDto.java
src/main/java/com/yapp/project/account/domain/dto/SocialDto.java
src/main/java/com/yapp/project/account/service/AccountService.java
src/main/java/com/yapp/project/account/service/AuthService.java
src/main/java/com/yapp/project/aux/test/account/AccountTemplate.java
src/test/java/com/yapp/project/account/controller/AccountControllerTest.java
src/test/java/com/yapp/project/account/controller/AuthControllerTest.java
src/test/java/com/yapp/project/account/domain/dto/AccountUserSocialRequestDtoTest.java
src/test/java/com/yapp/project/account/service/AccountServiceTest.java
src/test/java/com/yapp/project/account/service/AuthServiceTest.java

- AccountDto 이름 변경
- login, signup이 공통으로 쓰이는 곳이 있어서 @Transactional 제거하고 normalLogin, normalSignup메소드 추가

[YAPPIOS-58] DTO  이름 변경

---

src/main/java/com/yapp/project/routine/controller/RoutineController.java
src/main/java/com/yapp/project/routine/domain/Routine.java
src/main/java/com/yapp/project/routine/service/RoutineService.java
src/test/java/com/yapp/project/routine/RoutineServiceTest.java

루틴 수정 및 삭제 API 구현
- 루틴 수정하기 구현
- 루틴 수정하기 테스트 케이스 작성
- 루틴 삭제하기 구현
- 두 기능 Swagger 적용

[YAPPIOS-47] 루틴 수정 및 삭제 API 구현

---

src/main/java/com/yapp/project/account/domain/Account.java
src/main/java/com/yapp/project/account/domain/SocialType.java
src/main/java/com/yapp/project/account/domain/dto/AccountDto.java
src/main/java/com/yapp/project/account/service/AuthService.java
src/main/java/com/yapp/project/account/util/PasswordUtil.java
src/main/java/com/yapp/project/aux/test/account/AccountTemplate.java
src/main/java/com/yapp/project/config/exception/Content.java
src/main/java/com/yapp/project/config/exception/account/NotValidateException.java
src/test/java/com/yapp/project/account/domain/dto/AccountUserSocialRequestDtoTest.java
src/test/java/com/yapp/project/account/service/AuthServiceTest.java
src/test/java/com/yapp/project/saying/domain/SayingTest.java

- 비밀번호 정규식 강화
- 유저 일반 로그인 소셜타입 추가

[YAPPIOS-67]  유저 비밀번호 정규식 강화

---

src/main/java/com/yapp/project/account/domain/dto/AccountDto.java
src/main/java/com/yapp/project/account/domain/dto/SocialDto.java
src/main/java/com/yapp/project/account/domain/dto/TokenDto.java
src/main/java/com/yapp/project/account/domain/dto/TokenRequestDto.java
src/main/java/com/yapp/project/organization/domain/dto/OrgDto.java
src/main/java/com/yapp/project/saying/domain/dto/SayingDto.java

[YAPPIOS-72] 스웨거 문서 강화 작업 완료

---

src/main/java/com/yapp/project/mission/domain/Achievement.java
src/main/java/com/yapp/project/mission/domain/Capture.java
src/main/java/com/yapp/project/mission/domain/Mission.java

[YAPPIOS-75] 모델링 재작업

---

src/main/java/com/yapp/project/saying/controller/SayingController.java
src/main/java/com/yapp/project/saying/domain/dto/SayingDto.java
src/main/java/com/yapp/project/saying/service/SayingService.java
src/main/java/com/yapp/project/saying/utils/SayingUtils.java
src/test/java/com/yapp/project/saying/service/SayingServiceTest.java

- 메세지로 변환하는 작업 dto에 메소드로 변환
- 테스트케이스 추가

[YAPPIOS-80] 명언 오늘 했는 지 확인하는 기능 추가

---

src/main/java/com/yapp/project/account/controller/AccountController.java
src/main/java/com/yapp/project/account/domain/dto/AccountDto.java
src/main/java/com/yapp/project/account/service/AuthService.java
src/main/java/com/yapp/project/account/util/SecurityUtil.java
src/main/java/com/yapp/project/aux/content/AccountContent.java
src/main/java/com/yapp/project/mission/domain/dto/MissionDto.java
src/main/java/com/yapp/project/mission/service/MissionService.java
src/main/java/com/yapp/project/organization/controller/OrganizationController.java
src/main/java/com/yapp/project/organization/domain/dto/OrgDto.java
src/main/java/com/yapp/project/organization/service/GroupService.java
src/main/java/com/yapp/project/saying/service/SayingService.java
src/test/java/com/yapp/project/account/service/AuthServiceTest.java

[YAPPIOS-80] 명시화 작업

---

src/main/java/com/yapp/project/config/exception/retrospect/InvalidRetrospectUpdateException.java
src/main/java/com/yapp/project/config/exception/retrospect/RetrospectContent.java
src/main/java/com/yapp/project/config/exception/retrospect/RetrospectExceptionHandler.java
src/main/java/com/yapp/project/retrospect/service/RetrospectService.java

화고 수정 예외경우 추가
- 3일 지난 회고 수정 불가

[YAPPIOS-98] 3일 지난 회고 수정 불가 적용(ex 27일 작성 회고는 29일까지 수정 가능)

---

build.gradle
src/main/java/com/yapp/project/capture/controller/CaptureController.java
src/main/java/com/yapp/project/config/exception/GlobalExceptionHandler.java
src/main/java/com/yapp/project/config/exception/account/AccountExceptionHandler.java
src/main/java/com/yapp/project/config/exception/capture/CaptureExceptionHandler.java
src/main/java/com/yapp/project/config/exception/mission/MissionExceptionHandler.java
src/main/java/com/yapp/project/config/exception/report/WeekReportExceptionHandler.java
src/main/java/com/yapp/project/config/exception/retrospect/RetrospectExceptionHandler.java
src/main/java/com/yapp/project/config/exception/routine/RoutineExceptionHandler.java
src/main/java/com/yapp/project/config/exception/saying/SayingExceptionHandler.java
src/main/java/com/yapp/project/retrospect/controller/RetrospectController.java

- 센트리 연결
- 이미지 URL 프로퍼티로 설정
- 기본 프로퍼티 추가사함 있음
- 이미지 url 프로퍼티로 변경
- 센트리 프로퍼티 추가

[YAPPIOS-121] 센트리 연결 및 설정 변경

---

build.gradle
src/main/java/com/yapp/project/aux/AlertService.java
src/main/java/com/yapp/project/batch/scheduler/GroupScheduler.java
src/main/java/com/yapp/project/config/AppConfig.java
src/main/java/com/yapp/project/config/exception/GlobalExceptionHandler.java
src/main/java/com/yapp/project/config/exception/account/AccountExceptionHandler.java
src/main/java/com/yapp/project/config/exception/capture/CaptureExceptionHandler.java
src/main/java/com/yapp/project/config/exception/mission/MissionExceptionHandler.java
src/main/java/com/yapp/project/config/exception/report/WeekReportExceptionHandler.java
src/main/java/com/yapp/project/config/exception/retrospect/RetrospectExceptionHandler.java
src/main/java/com/yapp/project/config/exception/routine/RoutineExceptionHandler.java
src/main/java/com/yapp/project/config/exception/saying/SayingExceptionHandler.java

- Slack 연동 작업 성공
- 컨플런스에 application 관련 내용 추가

[YAPPIOS-127] slack 연동 작업

---

src/main/java/com/yapp/project/account/service/AccountService.java
src/main/java/com/yapp/project/report/domain/MonthRoutineReport.java
src/main/java/com/yapp/project/report/domain/MonthRoutineReportRepository.java
src/main/java/com/yapp/project/report/domain/WeekReport.java
src/main/java/com/yapp/project/report/domain/WeekReportRepository.java
src/main/java/com/yapp/project/routine/domain/Routine.java

[YAPPIOS-107] 유저 삭제시 루틴, 주-월리포트 관계 끊기

---

src/main/java/com/yapp/project/aux/test/report/ReportTemplate.java
src/main/java/com/yapp/project/report/domain/RoutineResult.java
src/main/java/com/yapp/project/report/domain/WeekReport.java
src/main/java/com/yapp/project/report/domain/dto/ReportDTO.java
src/main/java/com/yapp/project/report/service/ReportService.java

주리포트 발급 로직(수행 여부 계산) 최적화
- 기존 비슷한 반복 로직 제거
- 계산 로직 수정
- 로직 변경으로 인한 도메인 속성 수정

[YAPPIOS-101] 주리포트 발급 로직(수행 여부 계산) 최적화

---

src/main/java/com/yapp/project/batch/job/GroupConfig.java
src/main/java/com/yapp/project/batch/scheduler/GroupScheduler.java

- UTC 15시 30분은 한국 시간 기준으로 0시30분
- 미션 갯수 체크하도록 슬랙 전달

[YAPPIOS-130] 로깅 개선 작업

---

src/main/java/com/yapp/project/aux/alert/AlertService.java
src/main/java/com/yapp/project/aux/alert/SlackChannel.java
src/main/java/com/yapp/project/batch/job/GroupConfig.java
src/main/java/com/yapp/project/batch/scheduler/GroupScheduler.java
src/main/java/com/yapp/project/config/exception/GlobalExceptionHandler.java
src/main/java/com/yapp/project/config/exception/account/AccountExceptionHandler.java
src/main/java/com/yapp/project/config/exception/capture/CaptureExceptionHandler.java
src/main/java/com/yapp/project/config/exception/mission/MissionExceptionHandler.java
src/main/java/com/yapp/project/config/exception/report/WeekReportExceptionHandler.java
src/main/java/com/yapp/project/config/exception/retrospect/RetrospectExceptionHandler.java
src/main/java/com/yapp/project/config/exception/routine/RoutineExceptionHandler.java
src/main/java/com/yapp/project/config/exception/saying/SayingExceptionHandler.java

- 에러, 배치 채널 분리작업 실시
- 크론 '초' 위치에 0 을 삽입
- SlackChannel.java 추가

[YAPPIOS-130] 채널 분리

---

src/main/java/com/yapp/project/account/domain/dto/SocialDto.java
src/main/java/com/yapp/project/account/domain/oauth/SocialProperty.java
src/main/java/com/yapp/project/account/domain/oauth/kakao/KakaoResponse.java
src/main/java/com/yapp/project/account/service/AuthService.java
src/main/java/com/yapp/project/aux/request/ApiService.java
src/main/java/com/yapp/project/config/RestTemplateConfig.java

- RestTemplate을 활용하여 처리
- Id값만 필요하므로 @JsonIgnoreProperties(ignoreUnknown = true) 을 이용하여 처리

[YAPPIOS-133] 소셜 토큰 KAKAO 받아 왔을 때 인증처리 로직 추가

---

build.gradle
src/main/java/com/yapp/project/account/domain/Account.java
src/main/java/com/yapp/project/aux/common/DateUtil.java
src/main/java/com/yapp/project/report/service/ReportService.java
src/test/java/com/yapp/project/report/MonthReportServiceTest.java
src/test/java/com/yapp/project/report/WeekReportServiceTest.java
src/test/java/com/yapp/project/report/template/MonthReportTemplate.java
src/test/java/com/yapp/project/report/template/WeekReportTemplate.java
src/test/java/com/yapp/project/routine/RoutineServiceTest.java
src/test/java/com/yapp/project/routine/RoutineTemplate.java

주리포트 발급 4주치 시나리오 단위 테스트 작성 및 테스트를 위한 템플릿 위치 이동
- 주리포트 발급 단위 테스트 작성
- 테스트 시나리오 첨부
- [루틴 시나리오](https://github.com/YAPP-19th/iOS-Team-1-Backend/files/7491285/2021.9.24.pdf)
- 테스트를 위한 객체 생성 템플릿 위치 test 디렉토리 안으로 이동

[YAPPIOS-123] 주리포트 발급 4주치 시나리오 단위 테스트 작성 및 테스트를 위한 템플릿 위치 이동

---

src/main/java/com/yapp/project/aux/content/CaptureContent.java
src/main/java/com/yapp/project/capture/service/CaptureService.java
src/main/java/com/yapp/project/config/exception/capture/CaptureExceptionHandler.java
src/main/java/com/yapp/project/config/exception/capture/NotTodayCaptureException.java
src/main/java/com/yapp/project/mission/domain/Mission.java
src/main/java/com/yapp/project/report/service/ReportService.java
src/main/java/com/yapp/project/retrospect/service/RetrospectService.java
src/main/java/com/yapp/project/routine/domain/Week.java
src/main/java/com/yapp/project/routine/service/RoutineService.java
src/test/java/com/yapp/project/capture/service/CaptureServiceTest.java

- 테스트케이스 추가
- lint 적용 안된 부분 적용

[YAPPIOS-142] 캡처 날짜 확인하는 로직 추가

---

src/main/java/com/yapp/project/batch/job/MissionConfig.java
src/main/java/com/yapp/project/batch/scheduler/GroupScheduler.java
src/main/java/com/yapp/project/batch/scheduler/MissionScheduler.java
src/main/java/com/yapp/project/mission/domain/Mission.java
src/test/java/com/yapp/project/batch/job/GroupConfigTest.java
src/test/java/com/yapp/project/batch/job/MissionConfigTest.java
src/test/java/com/yapp/project/batch/job/TestBatchLegacyConfig.java

- 테스트케이스 추가
- 미션 관련 스케줄러 및 배치 작업 설정
- 미션 실패 횟수 업데이트 관련 메소드 추가

[YAPPIOS-143] 미션 실패 관련 배치 작업 설정

---

src/main/java/com/yapp/project/batch/job/ReportConfig.java
src/main/java/com/yapp/project/batch/scheduler/ReportScheduler.java
src/main/java/com/yapp/project/batch/scheduler/SchedulerConfig.java
src/main/java/com/yapp/project/report/service/ReportService.java
src/main/java/com/yapp/project/retrospect/service/RetrospectService.java

주 리포트와 월 리포트 배치 전략 설계 및 적용
- 주, 월 리포트 발급 배치 구현
- 주 리포트
- 매 수요일 02시 진행
- 월 리포트
- 매 1일 03시 진행
- Retrospect 이미지 경로 설정 변수 처리
- 주 리포트 발급을 위한 필요한 루틴 필터 처리 적용

[YAPPIOS-122] 주 리포트와 월 리포트 배치 전략 설계 및 적용

---

src/main/java/com/yapp/project/retrospect/domain/dto/RetrospectDTO.java
src/main/java/com/yapp/project/retrospect/service/RetrospectService.java
src/test/java/com/yapp/project/retrospect/RetrospectServiceTest.java

회고 작성 요일(당일 포함 3일) 아닐경우 예외처리
- 회고 작성 요청 인자 작성일 추가
- 회고 작성 당일 포함 3일 범위 아닌 경우 BadRequest처리
- 회고 서비스 로직 변경으로 인한 테스트 케이스 수정

[YAPPIOS-147] 회고 작성 요일(당일 포함 3일) 아닐경우 예외처리

---

src/main/java/com/yapp/project/account/domain/Account.java
src/main/java/com/yapp/project/account/domain/dto/AccountDto.java
src/main/java/com/yapp/project/account/service/AuthService.java
src/main/java/com/yapp/project/account/util/PasswordUtil.java
src/main/java/com/yapp/project/aux/test/account/AccountTemplate.java
src/test/java/com/yapp/project/account/domain/dto/AccountUserSocialRequestDtoTest.java
src/test/java/com/yapp/project/account/service/AuthServiceTest.java
src/test/java/com/yapp/project/account/util/PasswordUtilTest.java

- FCM 토큰 값 관련 추가
- 비밀번호 정규식 효율성 좋게 변경

[YAPPIOS-145] FCM 토큰 요청값 추가 작업 실시

---

src/main/java/com/yapp/project/aux/common/DateUtil.java
src/main/java/com/yapp/project/aux/test/mission/MissionTemplate.java
src/main/java/com/yapp/project/batch/job/GroupNotificationConfig.java
src/main/java/com/yapp/project/batch/scheduler/MissionNotificationScheduler.java
src/main/java/com/yapp/project/mission/domain/Cron.java
src/main/java/com/yapp/project/mission/domain/Mission.java
src/main/java/com/yapp/project/mission/domain/dto/MissionDto.java
src/main/java/com/yapp/project/mission/domain/repository/MissionRepository.java
src/main/java/com/yapp/project/mission/service/MissionService.java
src/test/java/com/yapp/project/mission/service/MissionServiceTest.java

- 노티 기능 추가
-  isAlarm 필드 추가
-  시작시간 추가

[YAPPIOS-157] 그룹 노티 기능 추가

---

src/main/java/com/yapp/project/account/controller/AuthController.java
src/main/java/com/yapp/project/account/domain/dto/AccountDto.java
src/main/java/com/yapp/project/account/domain/dto/SocialDto.java
src/main/java/com/yapp/project/account/service/AuthService.java
src/test/java/com/yapp/project/account/controller/AuthControllerTest.java
src/test/java/com/yapp/project/account/service/AuthServiceTest.java

- 로그인 dto 수정
- 스웨거에서 getter도 읽어들여서 클라쪽에서 혼란을 주기에 수정

[YAPPIOS-162] 로그인 DTO 수정

---

src/main/java/com/yapp/project/account/controller/AccountController.java
src/main/java/com/yapp/project/account/domain/Account.java
src/main/java/com/yapp/project/account/service/AccountService.java
src/main/java/com/yapp/project/aux/content/AccountContent.java
src/main/java/com/yapp/project/aux/test/account/AccountTemplate.java
src/main/java/com/yapp/project/mission/service/MissionService.java
src/test/java/com/yapp/project/account/service/AccountServiceTest.java
src/test/java/com/yapp/project/mission/service/MissionServiceTest.java

- isAlarm 필드 추가
- 알람 설정 바꾸는 컨트롤러 기능 추가
- 해당 필드를 통해 사전 알람 보낼건지 체크하기

[YAPPIOS-169] 알람 필드 추가 및 기능 구현

---

src/main/java/com/yapp/project/account/domain/Account.java
src/main/java/com/yapp/project/account/service/AccountService.java
src/main/java/com/yapp/project/aux/common/AccountUtil.java
src/main/java/com/yapp/project/batch/job/MissionConfig.java
src/main/java/com/yapp/project/capture/controller/CaptureController.java
src/main/java/com/yapp/project/capture/domain/Capture.java
src/main/java/com/yapp/project/capture/domain/CaptureImage.java
src/main/java/com/yapp/project/capture/domain/repository/CaptureRepository.java
src/main/java/com/yapp/project/capture/service/CaptureService.java
src/main/java/com/yapp/project/mission/domain/Mission.java
src/main/java/com/yapp/project/mission/domain/repository/MissionRepository.java
src/main/java/com/yapp/project/mission/service/MissionService.java
src/test/java/com/yapp/project/account/service/AccountServiceTest.java
src/test/java/com/yapp/project/batch/job/GroupConfigTest.java
src/test/java/com/yapp/project/capture/service/CaptureServiceTest.java
src/test/java/com/yapp/project/mission/service/MissionServiceTest.java

미션과 캡처 관련 삭제 처리 로직 
- 영구 삭제로 처리
- 보완점은 참조 관계 삭제 부분이 안되는 부분이 있어서 현재 repository로 가져와서 처리중 해결방안 모색중

[YAPPIOS-182] Remove 기능 폐기, 영구삭제로 전환

---

src/main/java/com/yapp/project/account/domain/Account.java
src/main/java/com/yapp/project/aux/test/account/AccountTemplate.java
src/main/java/com/yapp/project/aux/test/capture/CaptureTemplate.java
src/main/java/com/yapp/project/aux/test/mission/MissionTemplate.java
src/main/java/com/yapp/project/aux/test/organization/OrganizationTemplate.java
src/main/java/com/yapp/project/mission/domain/Mission.java
src/main/java/com/yapp/project/mission/domain/repository/MissionRepository.java
src/main/java/com/yapp/project/organization/domain/Organization.java
src/main/java/com/yapp/project/organization/domain/repository/OrganizationRepository.java
src/test/java/com/yapp/project/batch/job/GroupConfigTest.java
src/test/java/com/yapp/project/batch/job/MissionConfigTest.java
src/test/java/com/yapp/project/mission/service/MissionServiceTest.java
src/test/java/com/yapp/project/organization/domain/repository/OrganizationRepositoryTest.java

- 이전 이슈 재사용성 높임
- 배치테스트 진행하고 이후 테스트 데이터들 제거
- JPA N+1 문제 해결 
- https://vixxcode.tistory.com/205

[YAPPIOS-188] JPA N+1 문제 해결

---

src/main/java/com/yapp/project/aux/test/organization/OrganizationTemplate.java
src/main/java/com/yapp/project/mission/domain/Mission.java
src/main/java/com/yapp/project/mission/domain/repository/MissionRepository.java
src/test/java/com/yapp/project/mission/domain/repository/MissionRepositoryTest.java

[YAPPIOS-191] Mission 관련 레포지토리 테스트케이스 추가

---

src/main/java/com/yapp/project/retrospect/domain/RetrospectRepository.java
src/main/java/com/yapp/project/routine/domain/Routine.java
src/main/java/com/yapp/project/routine/domain/RoutineDTO.java
src/main/java/com/yapp/project/routine/domain/RoutineRepository.java
src/test/java/com/yapp/project/routine/RoutineServiceTest.java

일별 루틴 수행률 응답 수정 및 남은 N+1 해결
- 0/0 케이스 처리
- 50% -> 50으로 응답 형식 수정
- Routine 및 Retrospect 조회 미해결 N+1 수정

[YAPPIOS-192] 일별 루틴 수행률 응답 수정 및 남은 N+1 해결

---

src/main/java/com/yapp/project/mission/domain/repository/MissionRepository.java
src/test/java/com/yapp/project/organization/domain/repository/OrganizationRepositoryTest.java

- 카데시안 곱이 생기지 않아서 @Query 삭제
- 테스트 멱등성을 위해 @Transactional 추가 및 테스트 코드 수정

[YAPPIOS-194] 테스트 코드 수정 및 JPA 수정

---

src/main/java/com/yapp/project/account/controller/AccountController.java
src/main/java/com/yapp/project/account/domain/Account.java
src/main/java/com/yapp/project/account/domain/dto/AccountDto.java
src/main/java/com/yapp/project/account/service/AccountService.java
src/main/java/com/yapp/project/aux/test/account/AccountTemplate.java
src/test/java/com/yapp/project/account/service/AccountServiceTest.java
src/test/java/com/yapp/project/mission/domain/repository/MissionRepositoryTest.java
src/test/java/com/yapp/project/mission/service/MissionServiceTest.java

- 값을 ?on=true/false로 받아서 명시적으로 설정가능하도록 설정
- api/vi/account/me 에서 응답값 필드 isAlarm 추가
- 그에 따른 테스트케이스 수정
- 글 정리 https://vixxcode.tistory.com/211

[YAPPIOS-208] 알람 토글 설정 변경

---

.gitignore
jenkinsfiles/Jenkinsfile_develop

환경에 따른 설정파일 적용
- properties -> yaml
- 실행 및 테스트 로컬에서 성공 확인
- prod와 test 설정 파일 구분 방법은 main과 test디렉토리에 각 설정파일 배치

[YAPPIOS-146] 환경에 따른 설정파일 적용

---

src/main/java/com/yapp/project/aux/StatusEnum.java
src/main/java/com/yapp/project/aux/content/NoticeContent.java
src/main/java/com/yapp/project/config/SecurityConfig.java
src/main/java/com/yapp/project/config/exception/notice/NoticeExceptionHandler.java
src/main/java/com/yapp/project/config/exception/notice/NoticeNotFoundException.java
src/main/java/com/yapp/project/notice/controller/NoticeController.java
src/main/java/com/yapp/project/notice/domain/Notice.java
src/main/java/com/yapp/project/notice/domain/dto/NoticeDto.java
src/main/java/com/yapp/project/notice/domain/repository/NoticeRepository.java
src/main/java/com/yapp/project/notice/service/NoticeService.java
src/main/resources/import.sql
src/test/java/com/yapp/project/notice/domain/repository/NoticeRepositoryTest.java
src/test/java/com/yapp/project/notice/service/NoticeServiceTest.java

- 시큐리티 permitAll 추가
- 공지사항 관련 엔티티 추가
- 공지사항 서비스, 컨트롤러 관련 설정

[YAPPIOS-209] 공지사항 관련 기능 추가

---

src/main/java/com/yapp/project/batch/job/OrganizationConfig.java
src/main/java/com/yapp/project/batch/scheduler/OrganizationScheduler.java
src/main/java/com/yapp/project/mission/domain/Mission.java
src/main/java/com/yapp/project/mission/domain/repository/MissionRepository.java
src/main/java/com/yapp/project/mission/service/MissionService.java
src/main/java/com/yapp/project/organization/domain/Organization.java
src/test/java/com/yapp/project/batch/job/OrganizationConfigTest.java
src/test/java/com/yapp/project/batch/job/TestBatchLegacyConfig.java
src/test/java/com/yapp/project/organization/domain/repository/OrganizationRepositoryTest.java

- 단위는 1분 단위로 할 예정
- 단위가 짧다 보니 알람은 오지 않도록 할 생각
- 테스트케이스 수정 및 추가

[YAPPIOS-189] 참여자 갯수 ONETOMANY에서 배치 작업으로 변환

---

src/main/java/com/yapp/project/report/controller/ReportController.java
src/main/java/com/yapp/project/report/domain/dto/ReportDTO.java
src/test/java/com/yapp/project/report/MonthReportServiceTest.java

월 리포트 조회 카테고리별 비율 추가 및 응답 형식 수정
- 카테고리별 비율 응답을 위한 로직 추가
- 응답 형식 수정
- (미라클모닝, miracle), (자기개발, self), (건강, health), (생활, daily), (기타, etc)
```json
{
"message": {
"status": "MONTH_REPORT_OK",
"msg": "월 리포트를 성공적으로 조회하였습니다."
},
"data": {
"weekRateList": [
"45%",
"30%",
"42%",
"42%"
],
"resultByCategory": {
"self": {
"rate": 0,
"routineReportList": []
},
"health": {
"rate": 40,
"routineReportList": [
{
"title": "달리기",
"category": "건강",
"fullyDoneRate": "44%",
"partiallyDoneRate": "25%",
"notDoneRate": "31%"
},
{
"title": "물마시기",
"category": "건강",
"fullyDoneRate": "52%",
"partiallyDoneRate": "15%",
"notDoneRate": "33%"
}
]
},
"miracle": {
"rate": 0,
"routineReportList": []
},
"etc": {
"rate": 0,
"routineReportList": []
},
"daily": {
"rate": 60,
"routineReportList": [
{
"title": "커피", …
```

[YAPPIOS-210] 월 리포트 조회 카테고리별 비율 추가 및 응답 형식 수정

---

src/main/java/com/yapp/project/report/controller/ReportController.java
src/main/java/com/yapp/project/report/domain/MonthRoutineReport.java
src/main/java/com/yapp/project/report/domain/RoutineResult.java
src/main/java/com/yapp/project/report/domain/WeekReport.java
src/main/java/com/yapp/project/report/domain/dto/ReportDTO.java
src/main/java/com/yapp/project/report/service/ReportService.java
src/main/java/com/yapp/project/routine/domain/Routine.java
src/main/java/com/yapp/project/routine/domain/RoutineDTO.java
src/main/java/com/yapp/project/routine/domain/RoutineRepository.java
src/test/java/com/yapp/project/report/MonthReportServiceTest.java
src/test/java/com/yapp/project/report/WeekReportServiceTest.java
src/test/java/com/yapp/project/report/template/MonthReportTemplate.java
src/test/java/com/yapp/project/report/template/WeekReportTemplate.java
src/test/java/com/yapp/project/retrospect/RetrospectServiceTest.java
src/test/java/com/yapp/project/routine/RoutineServiceTest.java
src/test/java/com/yapp/project/routine/RoutineTemplate.java

카테고리 타입 변경으로 인한 리팩토링
- 카테고리 Enum 변경으로 인한 기존 코드 리팩토링
- 수행률 응답 타입 모두 50% → 50 (String → Integer) 
- 테스트 케이스 수정
- 월 리포트 응답 형식 수정
- 루틴 별 resultByCategory 인덱스 순서 
- 0 - MIRACLE
- 1 - SELF
- 2 - HEALTH
- 3 - DAILY
- 4 -  MORNING
- 5 - ETC
```json
{
"message": {
"status": "MONTH_REPORT_OK",
"msg": "월 리포트를 성공적으로 조회하였습니다."
},
"data": {
"weekRateList": [
45,
30,
42,
42
],
"resultByCategory": [
{
"rate": 0,
"routineReportList": []
},
{
"rate": 0,
"routineReportList": []
},
{
"rate": 40,
"routineReportList": [
{
"title": "달리기",
"category": 2,
"fullyDoneRate": 44,
"partiallyDoneRate": 25,
"notDoneRate": 31
},
{
"title": "물마시기",
"category": 2,
"fullyDoneRate": 52,
"partiallyDoneRate": 15,
"notDoneRate": 33
}
]
},
{
"rate": 60,
"routineReportList": [
{
"title": "커피",
"category": 3,
"fullyDoneRate": 50, …
```

[YAPPIOS-214] 카테고리 타입 변경으로 인한 리팩토링

---

src/main/java/com/yapp/project/report/domain/MonthRoutineReport.java
src/main/java/com/yapp/project/report/domain/RoutineResult.java
src/main/java/com/yapp/project/report/domain/dto/ReportDTO.java
src/main/java/com/yapp/project/routine/domain/Routine.java
src/main/java/com/yapp/project/routine/domain/RoutineCategory.java
src/main/java/com/yapp/project/routine/service/RoutineService.java
src/test/java/com/yapp/project/report/MonthReportServiceTest.java
src/test/java/com/yapp/project/report/template/MonthReportTemplate.java
src/test/java/com/yapp/project/retrospect/RetrospectServiceTest.java
src/test/java/com/yapp/project/routine/RoutineServiceTest.java

카테고리-루틴 Enum작업 및 루틴, 회고, 리포트 파트에 반영
- 루틴 전용 카테고리 Enum 작성
- 루틴 전용 카테고리 Enum을 사용하는 파트 모두 수정

[YAPPIOS-228] 카테고리-루틴 Enum작업 및 루틴,회고, 리포트 파트에 반영

---

src/main/java/com/yapp/project/account/controller/AccountController.java
src/main/java/com/yapp/project/account/controller/AuthController.java
src/main/java/com/yapp/project/capture/controller/CaptureController.java
src/main/java/com/yapp/project/mission/controller/MissionController.java
src/main/java/com/yapp/project/saying/controller/SayingController.java

@RequestBody 애노테이션을 붙이지 않아서 생긴 요청값 null로 인한 에러

[YAPPIOS-233] @RequestBody 생략으로 인한 500에러 확인

---

src/main/java/com/yapp/project/routine/domain/RoutineDTO.java
src/main/java/com/yapp/project/routine/service/RoutineService.java
src/test/java/com/yapp/project/routine/RoutineServiceTest.java

루틴 응답 DTO 통일 리팩토링
- 모든 루틴 응답에 result 필드 추가

[YAPPIOS-228] 루틴 응답 DTO 통일 리팩토링

---

src/test/java/com/yapp/project/account/service/AuthServiceTest.java

- 서로 이야기했을 때 객체에 대해서 새로 생성했을 때 더티체킹이 되서 업데이트된다고 이야기가 나왔지만 테스트 결과 필드 부분만 바꿔도 업데이트가 되는 것을 볼 수 있음

[YAPPIOS-235] 더티체킹 테스트

---

src/main/java/com/yapp/project/capture/domain/repository/CaptureRepository.java
src/main/java/com/yapp/project/mission/domain/Mission.java
src/main/java/com/yapp/project/mission/domain/dto/MissionDto.java
src/main/java/com/yapp/project/mission/service/MissionService.java
src/test/java/com/yapp/project/mission/service/MissionServiceTest.java

- 만일 오늘 미션에 대해서 진행하는 날이 아니면 default로 false 값을 전달
- 그렇지 않고 미션에 대해서 진행을 하는 날이고 했다면 인증 마크 전달

[YAPPIOS-244] 내 mission 정보를 줄 때 오늘 미션 인증을 했는지 안 했는지 정보 표시 여부 전달

---

docs/pr_60.md

[YAPPIOS-245] Enum 활용 document 작성
